### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by k-0** [mboskamp/MMM-PIR#12]
The Screen is black and i only see my mouse...

I got following error:
^[[31mWARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: ReferenceError: NodeHelper is not defined^[[39m
^[[31m    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PIR/node_helper.js:11:18)^[[39m
^[[31m    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PIR/node_helper.js:67:3)^[[39m
^[[31m    at Module._compile (internal/modules/cjs/loader.js:711:30)^[[39m
^[[31m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)^[[39m
^[[31m    at Module.load (internal/modules/cjs/loader.js:620:32)^[[39m
^[[31m    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)^[[39m
^[[31m    at Function.Module._load (internal/modules/cjs/loader.js:551:3)^[[39m
^[[31m    at Module.require (internal/modules/cjs/loader.js:658:17)^[[39m
^[[31m    at require (internal/modules/cjs/helpers.js:20:18)^[[39m
^[[31m    at loadModule (/home/pi/MagicMirror/js/app.js:126:17)^[[39m
App threw an error during load
ReferenceError: NodeHelper is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PIR/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PIR/node_helper.js:67:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadModule (/home/pi/MagicMirror/js/app.js:126:17)
ReferenceError: NodeHelper is not defined
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PIR/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PIR/node_helper.js:67:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at loadModule (/home/pi/MagicMirror/js/app.js:126:17)

**Comment by lxne** [comment]
I get exactly the same error.
Any ideas out there how to solve it?

**Comment by lxne** [comment]
Got mine working.
See issue #10

**Comment by kjendal** [comment]
node_helper.js is missing 
`var NodeHelper = require("node_helper");`

**Comment by AceTheFace** [comment]
Thanks @kjendal. Your fix worked for me!
